resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/shield-9/ci-demo.git
      branch: master

jobs:
- name: ci-demo
  plan:
  - get: repository
    trigger: true
  - task: vet
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        dir: repository
        path: go
        args: 
        - vet
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        dir: repository
        path: go
        args: 
        - test -v -cover
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        dir: repository
        path: go
        args: 
        - build
