resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/shield-9/ci-demo.git
      branch: master

jobs:
- name: ci-demo
  plan:
  - get: repository
    trigger: true
  - task: vet
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        path: bash
        args: 
        - -c
        - |
          cd repository
          go vet
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        path: bash
        args: 
        - -c
        - |
          cd repository
          go test -v -cover
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repository
      run:
        path: bash
        args: 
        - -c
        - |
          cd repository
          go build
